// quotes.js — 首页每日名言（励志 / 学英语相关），随机展示一条
window.QUOTES = [
  '每天背 20 个词，一年就是 7000+。',
  'The secret of getting ahead is getting started.',
  '重复是记忆之母。',
  '今天的努力，是明天考场的底气。',
  '词汇量不是背出来的，是反复见出来的。',
  'A journey of a thousand miles begins with a single step.',
  '不会的单词，多见面几次就成了老朋友。',
  'Don’t watch the clock; do what it does. Keep going.',
  '把单词放进句子里，它才真正属于你。',
  '慢就是快，稳扎稳打胜过突击。',
  'Practice makes permanent.',
  '每一个熟记的单词，都是分数。',
  'Believe you can and you’re halfway there.',
  '背单词没有捷径，但有规律可循。',
  'Success is the sum of small efforts repeated day in and day out.',
  '今天多记一个词，高考少一份慌。',
  'Vocabulary is a dress-up for your thoughts.',
  '把困难词标记出来，它们就是你提分的关键。',
  'It always seems impossible until it’s done.',
  '复习比学习更重要，遗忘是常态，重来是方法。',
  '学习语言，是在别人的世界里遇见自己。',
  'The more you read, the more you know.',
  '坚持 21 天，习惯成自然。',
  '单词本没有那么难，难的是开始和坚持。',
  'Dream big, start small, act now.',
  '每一次复习，都是在和遗忘作战。',
  '学英语不是为了考试，而是多一扇看世界的窗。',
  'Better an hour every day than a day every month.',
  '你背的不是单词，是未来的选择权。'
];
